#!/bin/bash

# PUBLIC_HOSTNAME=$(curl -s ifconfig.me)
PUBLIC_HOSTNAME="YOUR_HOSTNAME_HERE"

SHOPPING_HOSTNAME=$PUBLIC_HOSTNAME
SHOPPING_ADMIN_HOSTNAME=$PUBLIC_HOSTNAME
REDDIT_HOSTNAME=$PUBLIC_HOSTNAME
GITLAB_HOSTNAME=$PUBLIC_HOSTNAME
WIKIPEDIA_HOSTNAME=$PUBLIC_HOSTNAME
MAP_HOSTNAME=$PUBLIC_HOSTNAME
HOMEPAGE_HOSTNAME=$PUBLIC_HOSTNAME

# Change ports as desired
SHOPPING_PORT=3306
SHOPPING_ADMIN_PORT=7565
REDDIT_PORT=8080
GITLAB_PORT=9001
WIKIPEDIA_PORT=42022
MAP_PORT=443
HOMEPAGE_PORT=80

# Original webarena ports
# SHOPPING_PORT=7770
# SHOPPING_ADMIN_PORT=7780
# REDDIT_PORT=9999
# GITLAB_PORT=8023
# WIKIPEDIA_PORT=8888
# MAP_PORT=3000
# HOMEPAGE_PORT=4399

SHOPPING_URL="http://${PUBLIC_HOSTNAME}:${SHOPPING_PORT}"
SHOPPING_ADMIN_URL="http://${PUBLIC_HOSTNAME}:${SHOPPING_ADMIN_PORT}/admin"
REDDIT_URL="http://${PUBLIC_HOSTNAME}:${REDDIT_PORT}/forums/all"
GITLAB_URL="http://${PUBLIC_HOSTNAME}:${GITLAB_PORT}/explore"
WIKIPEDIA_URL="http://${PUBLIC_HOSTNAME}:${WIKIPEDIA_PORT}/wikipedia_en_all_maxi_2022-05/A/User:The_other_Kiwix_guy/Landing"
MAP_URL="http://${PUBLIC_HOSTNAME}:${MAP_PORT}"

